version: '3'

services:
  customers-db-0:
    image: mysql:8.4.0
    container_name: customers-shard-0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ../docker-volumes/mysql-shard-0/mysql:/var/lib/mysql
      - ../docker-volumes/mysql-shard-0/mysql-conf:/etc/mysql/conf.d
      - ./data:/docker-entrypoint-initdb.d

  customers-db-1:
    image: mysql:8.4.0
    container_name: customers-shard-1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ../docker-volumes/mysql-shard-1/mysql:/var/lib/mysql
      - ../docker-volumes/mysql-shard-1/mysql-conf:/etc/mysql/conf.d
      - ./data:/docker-entrypoint-initdb.d

  customers-db-2:
    image: mysql:8.4.0
    container_name: customers-shard-2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ../docker-volumes/mysql-shard-2/mysql:/var/lib/mysql
      - ../docker-volumes/mysql-shard-2/mysql-conf:/etc/mysql/conf.d
      - ./data:/docker-entrypoint-initdb.d